---
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VER: "${NAUTOBOT_VER}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    dockerfile: "development/Dockerfile"
x-nautobot-base: &nautobot-base
  image: "nautobot_plugin_chatops_meraki/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
  env_file:
    - "dev.env"
    - "creds.example.env"
  tty: true

version: "3.4"
services:
  nautobot:
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
      - "redis"
    <<: *nautobot-build
    <<: *nautobot-base
  worker:
    entrypoint: "nautobot-server rqworker"
    depends_on:
      - "nautobot"
    healthcheck:
      disable: true
    <<: *nautobot-base
